version: "3"
services:
  devkitminimal:
    build:
      args:
        BASE_NAME: continuumio/miniconda3
        BASE_TAG: ${BASE_TAG:-latest}
        CONDA_VERSION: ${BASE_TAG:-23.5.0}
        http_proxy: ${http_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        https_proxy: ${https_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        no_proxy: ${no_proxy}
        ftp_proxy: ${ftp_proxy}
      context: ../
      dockerfile: docker/Dockerfile
      target: devkitminimal
    image: devkitminimal

  predictive_maintenance:
    image: predictive_maintenance:latest
    build:
      target: predictive_maintenance
    extends:
      service: devkitminimal

  jupyter_server:
    command: bash -c "source /opt/conda/bin/activate && conda activate predictive_maintenance_intel && jupyter notebook --notebook-dir=/workspace/devkit --ip 0.0.0.0 --port ${PORT:-8888} --no-browser --allow-root"
    environment:
      - PORT=${PORT:-8888}
      - WORKSPACE=${MOUNT_WORKSPACE}
      - DATA_DIR=${MOUNT_DATA_DIR}
      - OUTPUT_DIR=${MOUNT_OUTPUT_DIR}
    extends:
      service: predictive_maintenance
    expose:
    - "${PORT:-8888}"
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    privileged: true
    volumes:
      - "${WORKSPACE}:${MOUNT_WORKSPACE}"
      - "${DATA_DIR}:${MOUNT_DATA_DIR}"
      - "${OUTPUT_DIR}:${MOUNT_OUTPUT_DIR}"

  interactive:
    environment:
      - WORKSPACE=${MOUNT_WORKSPACE}
      - DATA_DIR=${MOUNT_DATA_DIR}
      - OUTPUT_DIR=${MOUNT_OUTPUT_DIR}
    extends:
      service: predictive_maintenance
    stdin_open: true 
    tty: true
    volumes:
      - "${WORKSPACE}:${MOUNT_WORKSPACE}"
      - "${DATA_DIR}:${MOUNT_DATA_DIR}"
      - "${OUTPUT_DIR}:${MOUNT_OUTPUT_DIR}"
